[workspace]
authors = ["希望能学会 <2080554836@qq.com>"]
channels = ["conda-forge"]
description = "腾讯新闻网页版自动化测试框架"
name = "tencent-news-web-test"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[dependencies]
nodejs = ">=25.8.2,<25.9"
python = "3.12.*"
pytest-rerunfailures = ">=16.1,<17"

[pypi-dependencies]
allure-pytest = ">=2.15.3,<3.0.0"
autoflake = ">=2.3.3,<3.0.0"
black = ">=26.3.1,<27.0.0"
isort = ">=8.0.1,<9.0.0"
playwright = ">=1.58.0,<2.0.0"
pytest = ">=9.0.3,<10.0.0"
tomli = ">=2.0.0,<3.0.0"

[tasks]
clean = "python scripts/clean.py"
install-playwright = "playwright install"
lint = "python scripts/lint.py"
run = "python scripts/run.py -m completed"
test = "python scripts/run.py -m inprogress"

[activation]
scripts = []

# playwright启动配置
[tool.playwright]
launch_options = {headless = true, timeout = 5000, args = ["--font-render-hinting=none"]} 
platform = "" # 测试平台：chromium、firefox、webkit，默认chromium

# autoflake配置
[tool.autoflake]
exclude = [".git", "__pycache__", ".vscode", "report", "data", ".log", ".md"]
expand-star-imports = true
ignore-init-module-imports = true
in-place = true
recursive = true
remove-all-unused-imports = true
remove-unused-variables = true

# 项目构建配置
[tool.build]
black = false
isort = false

# allure配置
[tool.allure]
enable = false
input = './report/json'
open_report = false
output = './report/html'
