[workspace]
name = "tencent-news-web-test"
version = "0.1.0"
description = "腾讯新闻网页版自动化测试框架"
authors = ["希望能学会 <2080554836@qq.com>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64"]

[dependencies]
python = "3.12.*"
nodejs = ">=25.8.2,<25.9"

[pypi-dependencies]
pytest = ">=9.0.3,<10.0.0"
playwright = ">=1.58.0,<2.0.0"
allure-pytest = ">=2.15.3,<3.0.0"
pytest-dependency = ">=0.6.1,<0.7.0"
autoflake = ">=2.3.3,<3.0.0"
black = ">=26.3.1,<27.0.0"
isort = ">=8.0.1,<9.0.0"
tomli = ">=2.0.0,<3.0.0"

[tasks]
install-playwright = "playwright install"
lint = "python scripts/lint.py"
run = "python scripts/run.py --mode run -m completed"
test = "python -c \"print('test')\""
# test = "python scripts/run.py --mode build -m inprogress"
clean = "python scripts/clean.py"

[activation]
scripts = []

# playwright启动配置
[tool.playwright]
launch_options = {headless = true, timeout = 3000, slow_mo = 1000}
platform = "" # 测试平台：chromium、firefox、webkit，默认chromium

# autoflake配置
[tool.autoflake]
in-place = true
recursive = true
remove-all-unused-imports = true
ignore-init-module-imports = true
remove-unused-variables = true
expand-star-imports = true
exclude = [".git", "__pycache__", ".vscode", "report", "data", ".log", ".md"]

# 项目构建配置
[tool.build]
black = false
isort = false

# allure配置
[tool.allure]
enable = true
input = './report/json'
open_report = false
output = './report/html'
