[workspace]
authors = ["希望能学会 <2080554836@qq.com>"]
channels = ["conda-forge"]
description = "新闻网站自动化测试工具"
name = "news-site-web-test"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[dependencies]
nodejs = ">=25.8.2,<25.9"
python = "3.12.*"
pytest-rerunfailures = ">=16.1,<17"
pytest-xdist = ">=3.8.0,<4"

[pypi-dependencies]
allure-pytest = ">=2.15.3,<3.0.0"
autoflake = ">=2.3.3,<3.0.0"
black = ">=26.3.1,<27.0.0"
isort = ">=8.0.1,<9.0.0"
playwright = ">=1.58.0,<2.0.0"
pytest = ">=9.0.3,<10.0.0"
tomli = ">=2.0.0,<3.0.0"
pytest-playwright = ">=0.7.0,<0.8.0"

[tasks]
clean = "python scripts/clean.py"
install-playwright = "playwright install"
lint = "python scripts/lint.py"
run = "python scripts/run.py -m completed"
test = "python scripts/run.py -m inprogress"

[activation]
scripts = []

# autoflake配置
[tool.autoflake]
exclude = [".git", "__pycache__", ".vscode", "report", "data", ".log", ".md"]
expand-star-imports = true
ignore-init-module-imports = true
in-place = true
recursive = true
remove-all-unused-imports = true
remove-unused-variables = true

# allure配置
[tool.allure]
enable = false
input = './report/json'
open_report = false
output = './report/html'
