[project]
authors = [
  {name = "希望能学会", email = "2080554836@qq.com"},
]
dependencies = [
  "pytest (>=9.0.3,<10.0.0)",
  "playwright (>=1.58.0,<2.0.0)",
  "allure-pytest (>=2.15.3,<3.0.0)",
  "pytest-dependency (>=0.6.1,<0.7.0)",
  "autoflake (>=2.3.3,<3.0.0)",
]
description = "腾讯新闻网页版自动化测试框架"
license = "MIT"
name = "tencent-news-web-test"
readme = "README.md"
requires-python = ">=3.14"
version = "0.1.0"

[dependency-groups]
dev = [
  "black (>=26.3.1,<27.0.0)",
  "isort (>=8.0.1,<9.0.0)",
]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=2.0.0,<3.0.0"]

[tool.poetry]
package-mode = false

[tool.autoflake]
in-place = true
recursive = true
remove-all-unused-imports = true
ignore-init-module-imports = true
remove-unused-variables = true
expand-star-imports = true
exclude = [".git", "__pycache__", ".vscode", "report", "data", ".log", ".md"]


[tool.pytest.ini_options]
addopts = "-v -s --alluredir=./report/json --clean-alluredir"
log_cli = true
log_date_format = "%Y-%m-%d %H:%M:%S"
log_file = './test_log.log'
log_file_mode = 'w'
log_format = "%(asctime)s\t%(levelname)s\t%(funcName)s\t%(lineno)d\t%(message)s"
log_level = "DEBUG"
minversion = "9.0.3"
python_files = ["test_*.py"]
testpaths = ["test_cases"]
markers = [ "completed: 已完成", "inprogress: 正在实现", "dependency: 测试用例依赖"]

[tool]
mode = 'build'  # run, build
screenshot_on_failure = true  # 在测试用例失败时截图

# 项目构建配置
[tool.build]
black = false
isort = false

# playwright启动配置
[tool.playwright]
launch_options = {headless = false, timeout = 3000, slow_mo = 1000} 
platform = "" # 测试平台：chromium、firefox、webkit，默认chromium

# allure配置
[tool.allure]
enable = false
input = './report/json'
open_report = true
output = './report/html'
