[pytest]
addopts = -v -s --alluredir=./report/json --clean-alluredir
log_cli = true
log_date_format = %Y-%m-%d %H:%M:%S
log_file = ./test_log.log
log_file_mode = w
log_format = %(asctime)s\t%(levelname)s\t%(funcName)s\t%(lineno)d\t%(message)s
log_level = DEBUG
minversion = 9.0.3
python_files = test_*.py
testpaths = test_cases
markers = 
    completed: 已完成
    inprogress: 正在实现
    dependency: 测试用例依赖
